version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.3.0
    commands:
      - bundle config set path vendor/bundle
      - bundle install --jobs 4 --retry 3

  pre_build:
    commands:
      - bundle exec rails db:create RAILS_ENV=test
      - bundle exec rails db:migrate RAILS_ENV=test

  build:
    commands:
      - bundle exec rspec

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - vendor/bundle/**/*